# Generated by Django 4.0.dev20210521113437 on 2021-07-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(choices=[('McL', 'McLaren'), ('Fr', 'Ferrari'), ('Mgn', 'Morgan'), ('Ms', 'Maserati')], default='Customer', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FGcode', models.CharField(max_length=10)),
                ('description', models.CharField(choices=[('FG1942', 'Coupe Deck'), ('FG1986', 'LH Coupe Fender'), ('FG1989', 'RH Coupe Fender'), ('FG2268', 'Tonneau'), ('FG2275', 'LH Spider Fender'), ('FG2279', 'RH Spider Fender'), ('FG2303', 'LH Door Assembly'), ('FG2304', 'RH Door Assembly')], max_length=120)),
                ('serial_number', models.CharField(max_length=12)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(choices=[('Forming', '1.Forming'), ('Trimming', '2.Trimming'), ('Chemi-Clean', '3.Chemi-Clean'), ('Re-Strike', '4.Re-Strike'), ('Goods-In Inspection', '5.Goods-In Inspection'), ('Pre-Assembly', '6.Pre-Assembly'), ('Assembly', '7.Assembly'), ('A-Class', '8.A-Class'), ('Gap and Flush', '9.Gap and Flush'), ('Heat Treatment', '10.Heat Treatment'), ('Final Inspection', '11.Final Inspection')], max_length=20)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('operation_status', models.CharField(choices=[('p', 'Passed'), ('s', 'Scrapped'), ('q', 'Quarantined')], default='What is the part status?', max_length=120)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.part')),
            ],
            options={
                'ordering': ['date_signed'],
            },
        ),
    ]
