# Generated by Django 4.0.dev20210521113437 on 2021-07-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_remove_part_operation_operation_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='part',
        ),
        migrations.AddField(
            model_name='operation',
            name='parts',
            field=models.ManyToManyField(null=True, related_name='_records_operation_parts_+', to='records.Part'),
        ),
    ]
