# Generated by Django 4.0.dev20210521113437 on 2021-07-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_remove_operation_part_operation_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='parts',
        ),
        migrations.AddField(
            model_name='part',
            name='operation',
            field=models.ManyToManyField(help_text='Select an operation for this part', to='records.Operation'),
        ),
    ]
