# Generated by Django 4.0.dev20210521113437 on 2021-07-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_remove_operation_parts_part_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_status',
            field=models.CharField(choices=[('Passed', 'P'), ('Scrapped', 'S'), ('Quarantined', 'Q')], default='What is the part status?', max_length=120),
        ),
    ]
